[package]
name = "mount_arelle"
version = "0.1.0"
authors = ["Adam <adamsimeth@gmail.com>"]

[dependencies]
rand = "0.3.16"
image = "0.15.0"

ggez = "0.3.3"

serde = "1.0.11"
serde_derive = "1.0"
serde_json = "1.0.2"
